import Head from "next/head";
import Image from "next/image";
import Subject from "../components/Sub";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Edu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-wrap justify-center align-middle px-10 mt-4">
        <Subject />
        <Subject />
        <Subject />
      </div>
    </div>
  );
}
